### ISSUE TITLE
File not found in subdirectory

### ISSUE THREAD

**Issue by EchoPouet** [kernoeb/docker-docsify-pdf#1] opened 2022-07-19 15:52 UTC
Hello, I think that the subdirectories aren't supported.

My `_sidebar.md` is:
```markdown
<!-- docs/_sidebar.md -->

* [Home](/)
* [Tutorials](/Tutorials/)
  * [Documentation](/Tutorials/Documentation/Contribute.md)
* [Installation](/Installation/)
  * [Docker setup](/Installation/Docker-setup.md)
  * [Mount the sources](/Installation/Mount-the-sources.md)
* [Contact](/Contact.md)
* [Doxygen](/Doxygen.md)
```

And the convertor's result is:
```bash
docker run --rm -it \                 
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:latest
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: updating user 'node' to UID '977293986'
fixuid: updating group 'node' to GID '977273345'
fixuid: recursively searching path /home/node/pdf
fixuid: recursively searching path /home/node/.static
fixuid: chown /home/node/.static
fixuid: recursively searching path /home/node/resources
fixuid: chown /home/node/resources
fixuid: chown /home/node/resources/css
fixuid: chown /home/node/resources/css/vue.css
fixuid: chown /home/node/resources/js
fixuid: chown /home/node/resources/js/docsify.js
fixuid: chown /home/node/resources/js/icons.js
fixuid: chown /home/node/resources/js/prism-bash.min.js
fixuid: chown /home/node/resources/js/prism-json.min.js

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



ERROR:
combineMarkdowns

Error: file /Tutorials/Documentation/Contribute.md is not exist, but listed in docs/_sidebar.md



ERROR:
run error

Error: file /Tutorials/Documentation/Contribute.md is not exist, but listed in docs/_sidebar.md
```

Also, `[Tutorials](/Tutorials/)` hasn't file name because by default the `README.md` file is taken (/Tutorials/README.md).

**Comment by kernoeb** [comment] 2022-07-19 15:59
Hello!

I'm currently on vacation without my computer so I can't try to reproduce this..

But maybe it's related to the `/` at the start of every paths ? It's possible the combine function is trying to find the file at the root of the container 🤔

(If you can, I think you can debug this by trying with node directly)

**Comment by EchoPouet** [comment] 2022-07-20 09:14
I can wait your return :smile:  I will be on vacation soon.

**Comment by kernoeb** [comment] 2022-07-28 08:29
Hello, I confirm this is related to the `/` on your sidebar
In the example, 

```
* [Documentation](README.md)
* [1 - Use Case](/usecase/README.md)
    * [1.1 - Never Gonna Give You Up](/usecase/example.md)
```

![image](https://user-images.githubusercontent.com/24623168/181458868-600fa7a1-47a3-4069-aed1-775b5fd63c57.png)

will not work, but

```
* [Documentation](README.md)
* [1 - Use Case](usecase/README.md)
    * [1.1 - Never Gonna Give You Up](usecase/example.md)
```

is working

I don't think it should be fixed, even if it may work in Docsify (`/` -> root of the project), it's a big ambiguous 
If you can just change your sidebar (remove the `/`), it's great, otherwise tell me and i'll may add an optional parameter/environment variable to handle this case :+1:

**Comment by EchoPouet** [comment] 2022-07-28 09:37
OK thanks I'll check witou `/`.

**Comment by EchoPouet** [comment] 2022-07-29 09:23
Unfortunately I have another problem:
```bash
docker run --rm -it \ 
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs-pdf-test:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:latest
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: updating user 'node' to UID '977293986'
fixuid: updating group 'node' to GID '977273345'
fixuid: recursively searching path /home/node/pdf
fixuid: recursively searching path /home/node/.static
fixuid: chown /home/node/.static
fixuid: recursively searching path /home/node/resources
fixuid: chown /home/node/resources
fixuid: chown /home/node/resources/css
fixuid: chown /home/node/resources/css/vue.css
fixuid: chown /home/node/resources/js
fixuid: chown /home/node/resources/js/docsify.js
fixuid: chown /home/node/resources/js/icons.js
fixuid: chown /home/node/resources/js/prism-bash.min.js
fixuid: chown /home/node/resources/js/prism-json.min.js

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



ERROR:
combineMarkdowns

Error: EISDIR: illegal operation on a directory, read


ERROR:
run error

Error: EISDIR: illegal operation on a directory, read
```

I'm owner of this folder. I give you my test folder to your debug -> [docs-pdf-test.zip](https://github.com/kernoeb/docker-docsify-pdf/files/9218590/docs-pdf-test.zip)

**Comment by kernoeb** [comment] 2022-07-29 09:44
Hello, 

`* [Tutorials](Tutorials/)` should be `* [Tutorials](Tutorials/README.md)`

But you're right, it should works without README.md, I'll fix this after work
While waiting for my fix, you can add `README.md` on Tutorials, Installation and Concepts (no directories on the sidebar)

**Comment by EchoPouet** [comment] 2022-07-29 09:53
Yes is better to respect the docsify syntax.

I add `README.md` to try. The pdf is generated but I have an error with the cover.

```bash
docker run --rm -it \                                                             
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs-pdf-test:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:latest
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: updating user 'node' to UID '977293986'
fixuid: updating group 'node' to GID '977273345'
fixuid: recursively searching path /home/node/pdf
fixuid: recursively searching path /home/node/.static
fixuid: chown /home/node/.static
fixuid: recursively searching path /home/node/resources
fixuid: chown /home/node/resources
fixuid: chown /home/node/resources/css
fixuid: chown /home/node/resources/css/vue.css
fixuid: chown /home/node/resources/js
fixuid: chown /home/node/resources/js/docsify.js
fixuid: chown /home/node/resources/js/icons.js
fixuid: chown /home/node/resources/js/prism-bash.min.js
fixuid: chown /home/node/resources/js/prism-json.min.js

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



Serving /home/node now.
Listening at http://localhost:17000


INFO:
Version : HeadlessChrome/102.0.5005.61

{
  format: 'a4',
  printBackground: true,
  landscape: false,
  headerTemplate: '<div style="display: none"></div>',
  footerTemplate: '<p style="margin: auto;text-align: center;font-size: 8px;"><span class="pageNumber"></span>&nbsp;/&nbsp;<span class="totalPages"></span></p>',
  displayHeaderFooter: true,
  path: '/home/node/pdf/DOCUMENTATION.pdf',
  margin: { left: '1cm', right: '1cm', top: '1cm', bottom: 70 },
  timeout: 560000
}

INFO:
rendering cover


ERROR:
puppeteer renderer error:

Error: Error merging cover and pdf: Error: Command failed: java -jar /home/node/node_modules/.pnpm/easy-pdf-merge@0.2.6/node_modules/easy-pdf-merge/jar/pdfbox.jar PDFMerger "/home/node/resources/cover.pdf" "/home/node/pdf/DOCUMENTATION.pdf" "/home/node/pdf/DOCUMENTATION.pdf"
Exception in thread "main" java.io.FileNotFoundException: /home/node/resources/cover.pdf (Is a directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at org.apache.pdfbox.io.RandomAccessBufferedFileInputStream.<init>(RandomAccessBufferedFileInputStream.java:99)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1079)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1006)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.legacyMergeDocuments(PDFMergerUtility.java:451)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.mergeDocuments(PDFMergerUtility.java:346)
	at org.apache.pdfbox.tools.PDFMerger.merge(PDFMerger.java:70)
	at org.apache.pdfbox.tools.PDFMerger.main(PDFMerger.java:49)
	at org.apache.pdfbox.tools.PDFBox.main(PDFBox.java:81)
```

**Comment by kernoeb** [comment] 2022-07-29 09:58
Did you replace this file : https://github.com/kernoeb/docker-docsify-pdf/blob/main/resources/covers/cover.pdf ?

If you don't want any cover, just remove this line : `-v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro`

**Comment by kernoeb** [comment] 2022-07-29 10:11
Maybe you can try the README.md fix for directories using the `ghcr.io/kernoeb/docker-docsify-pdf:main` image

Now, if the file written in a sidebar is a directory, `README.md` is added

https://github.com/kernoeb/docker-docsify-pdf/commit/ce8e404637201ba2b712053e2a830fef30fd0e83

**Comment by EchoPouet** [comment] 2022-07-29 11:45
Ok it's work if remove cover and without `README.md`.

But without `README.md`, in TOC "Tutotials" link doesn't work.

**Comment by kernoeb** [comment] 2022-07-29 11:50
Even with the main image ?

**Comment by EchoPouet** [comment] 2022-07-29 11:54
Yes

**Comment by kernoeb** [comment] 2022-08-23 20:38
Hello, I'm sorry, I was really busy these last weeks (and I didn't use docsify since 1 month too)

I just commited a fix in the main branch, that allows to avoid the `.md` extension (in sidebar or in markdown files)

I added an example on the `docs/` directory, can you check if it's ok now ? I maybe forgot some cases, and I tried to make the code more robust

**Comment by johnholliday** [comment] 2022-08-24 04:12
I'm also getting the same result:
```
INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js,/home/node/resources/js/prism-python.min.js

INFO:
Build with settings:
{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}

ERROR:
combineMarkdowns

Error: ENOENT: no such file or directory, open '/README.md'

ERROR:
run error

Error: ENOENT: no such file or directory, open '/README.md'
```

**Comment by kernoeb** [comment] 2022-08-24 07:19
Hello,

As decribed before, you should probably don't write your sidebar with slash (like `/README.md`)

For this tool, `/` is the root of the container... but maybe I can add an util function that replace `/` with the root of the docs library ?

**Comment by kernoeb** [comment] 2022-08-24 07:36
Does it works for you now ?

I tried to support the both cases

<img width="531" alt="image" src="https://user-images.githubusercontent.com/24623168/186358917-59fd5367-0462-4d96-815d-797acc03dd8a.png">

**Comment by EchoPouet** [comment] 2022-08-24 08:32
With this version -> **ghcr.io/kernoeb/docker-docsify-pdf:main**, my pdf has only the cover :(

No output error.

```shell
docker run --rm -it \
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/pdf/my-cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=my-doc.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:main
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: updating user 'node' to UID '977293986'
fixuid: updating group 'node' to GID '977273345'
fixuid: recursively searching path /home/node/pdf
fixuid: recursively searching path /home/node/.static
fixuid: chown /home/node/.static
fixuid: recursively searching path /home/node/resources
fixuid: chown /home/node/resources
fixuid: chown /home/node/resources/css
fixuid: chown /home/node/resources/css/vue.css
fixuid: chown /home/node/resources/js
fixuid: chown /home/node/resources/js/docsify.js
fixuid: chown /home/node/resources/js/icons.js
fixuid: chown /home/node/resources/js/prism-bash.min.js
fixuid: chown /home/node/resources/js/prism-json.min.js
fixuid: chown /home/node/resources/js/prism-python.min.js

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js,/home/node/resources/js/prism-python.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/my-doc.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



Serving /home/node now.
Listening at http://localhost:17000


INFO:
Version : HeadlessChrome/102.0.5005.173

{
  format: 'a4',
  printBackground: true,
  landscape: false,
  headerTemplate: '<div style="display: none"></div>',
  footerTemplate: '<p style="margin: auto;text-align: center;font-size: 8px;"><span class="pageNumber"></span>&nbsp;/&nbsp;<span class="totalPages"></span></p>',
  displayHeaderFooter: true,
  path: '/home/node/pdf/my-doc.pdf',
  margin: { left: '1cm', right: '1cm', top: '1cm', bottom: 70 },
  timeout: 560000
}

INFO:
rendering cover


SUCCESS:
cover merged


SUCCESS:
/home/node/pdf/my-doc.pdf
```

**Comment by kernoeb** [comment] 2022-08-24 08:35
Hmm, I tried with the zip you sent me last time, it works 🤔

**Comment by EchoPouet** [comment] 2022-08-24 08:42
Yes sorry, I changed my sidebar to work with previous version but with "/" it's work now without add **README.md** in path. Great !

```markdown
<!-- docs/_sidebar.md -->

* [Home](/)
* [Concepts](/Concepts)
  * [Tools and libraries](/Concepts/Tools&libraries.md)
  * [ROS2 packages](/Concepts/ROS2-packages.md)
* [Installation](/Installation)


* [Doxygen](Doxygen.md)
```

**Comment by kernoeb** [comment] 2022-08-24 08:47
Cool ! 

I'm just waiting for @johnholliday to confirm, if it's good I will make a release 👍

**Comment by EchoPouet** [comment] 2022-08-24 09:05
I have an other problem, but it's not your fault.
I have a page with **platuml** files to generate graph and if I had it, the pdf is empty. No ouput error.

**Comment by kernoeb** [comment] 2022-08-24 09:07
Can you send me an example ? Maybe I can try to handle this case (or at least avoid the empty pdf)

**Comment by kernoeb** [comment] 2022-08-24 09:10
Hmm, you used the latest image here, can you try with main image ? 

And maybe with the `--user` flag too

**Comment by EchoPouet** [comment] 2022-08-24 09:15
My command:

 ```
docker run --rm -it \
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/pdf/my-cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=my-doc.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:main
```

If I remove following line it's OK:
```markdown
[do_make_fdisp](./plantuml/do_make_fdisp.puml ':include :type=code plantuml')
```

**Comment by johnholliday** [comment] 2022-08-24 09:30
Changing from 'latest' to 'main' without the --user option:

```
INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



ERROR:
combineMarkdowns

Error: ENOENT: no such file or directory, open '/README.md'



ERROR:
run error

Error: ENOENT: no such file or directory, open '/README.md'
```

Hard error with the --user flag (not sure I'm escaping the parameter correctly):

Modified script
```powershell
  docker run --rm -i `
  --cap-add=SYS_ADMIN `
  --user "`$(id -u):`$(id -g)" `
  -v "${pwd}/docs:/home/node/docs:ro" `
  -v "${pwd}/docs/_pdf:/home/node/pdf:rw" `
  -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" `
  ghcr.io/kernoeb/docker-docsify-pdf:main
```

Result:
```
docker: Error response from daemon: unable to find user $(id -u): no matching entries in passwd file.
```

**Comment by kernoeb** [comment] 2022-08-24 09:33
Did you pull the latest main ? (docker pull ghcr.io/kernoeb/docker-docsify-pdf:main) ?

**Comment by johnholliday** [comment] 2022-08-24 09:36
```powershell
  docker pull ghcr.io/kernoeb/docker-docsify-pdf:main
  
  docker run --rm -i `
  --cap-add=SYS_ADMIN `
  --user 1000:1000 `
  -v "${pwd}/docs:/home/node/docs:ro" `
  -v "${pwd}/docs/_pdf:/home/node/pdf:rw" `
  -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" `
  ghcr.io/kernoeb/docker-docsify-pdf:main
```

Result:

```
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'node' UID
fixuid: runtime GID '1000' already matches container group 'node' GID

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js,/home/node/resources/js/prism-python.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



ERROR:
markdown combining error

TypeError: Cannot read properties of undefined (reading 'children')



ERROR:
combineMarkdowns

TypeError: Cannot read properties of undefined (reading 'children')



ERROR:
run error

TypeError: Cannot read properties of undefined (reading 'children')
```

**Comment by kernoeb** [comment] 2022-08-24 09:39
Arf...

I think this error is related to markdown top titles (`# 1.1 - Title`) 
Maybe you have a markdown without any title or something ?

Can you give me an example directory ? I can try to reproduce this

**Comment by johnholliday** [comment] 2022-08-24 09:54
[docs.zip](https://github.com/kernoeb/docker-docsify-pdf/files/9415021/docs.zip)

**Comment by kernoeb** [comment] 2022-08-24 10:17
Hmm, except the `.puml` files which are not displayed correctly (I'm fixing this in https://github.com/kernoeb/docker-docsify-pdf/issues/2), I have no issue with your zip file

here's the command I'm using, in a Bash shell :

```bash
docker pull ghcr.io/kernoeb/docker-docsify-pdf:main

docker run --rm -it   --cap-add=SYS_ADMIN   --user $(id -u):$(id -g)   -v $(pwd)/docs:/home/node/docs:ro   -v $(pwd)/pdf:/home/node/pdf:rw   -v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro   -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" ghcr.io/kernoeb/docker-docsify-pdf:main
```

If like me you're on a Macbook M1 pro (ARM), you can try to build the image `docker build -t docsify-pdf-generator .` the use the `docsify-pdf-generator` image previously built

**Comment by johnholliday** [comment] 2022-08-24 10:39
Can you test it in PowerShell?  I'm on Windows 11 using PowerShell 7.2.6.

**Comment by johnholliday** [comment] 2022-08-24 10:50
I'm getting the same errors running in Ubuntu-20.04 (Windows Subsystem for Linux).
```
docker run --rm -it --cap-add=SYS_ADMIN --user $(id -u):$(id -g) -v $(pwd)/docs:/home/node/docs:ro -v $(pwd)/pdf:/home/node/pdf:rw -v $(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" ghcr.io/kernoeb/docker-docsify-pdf:main
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'node' UID
fixuid: runtime GID '1000' already matches container group 'node' GID

INFO:
/home/node/resources/js/docsify.js,/home/node/resources/js/icons.js,/home/node/resources/js/prism-bash.min.js,/home/node/resources/js/prism-json.min.js,/home/node/resources/js/prism-python.min.js


INFO:
Build with settings:

{
  pathToStatic: '.static',
  mainMdFilename: 'main.md',
  pathToPublic: 'pdf/DOCUMENTATION.pdf',
  contents: 'docs/_sidebar.md',
  pathToDocsifyEntryPoint: '.',
  cover: 'resources/cover.pdf'
}



ERROR:
markdown combining error

TypeError: Cannot read properties of undefined (reading 'children')



ERROR:
combineMarkdowns

TypeError: Cannot read properties of undefined (reading 'children')



ERROR:
run error

TypeError: Cannot read properties of undefined (reading 'children')
```

**Comment by kernoeb** [comment] 2022-08-24 11:30
I don't reproduce this on MacOS or Linux (Ubuntu based distro)

Sorry, I didn't have Docker installed on my Windows 11 computer, but I just installed it and tried with Docker (WSL2, not HyperV), it works too 🤔 

On Powershell, I needed of course to replace `/` with `\` and remove the `--user` part : 

```
docker run --rm -it   --cap-add=SYS_ADMIN    -v "$(pwd)\docs:/home/node/docs:ro"   -v "$(pwd)\pdf:/home/node/pdf:rw"   -v "$(pwd)\resources\covers\cover.pdf:/home/node/resources/cover.pdf:ro"   -e "PDF_OUTPUT_NAME=DOCUMENTATION.pdf" ghcr.io/kernoeb/docker-docsify-pdf:main
```

Is the zip file you sent me is identical to yours ?  
I think it's related to the markdown content, not the generation itself

Can you try with the default example in the git repo ?

**Comment by kernoeb** [comment] 2022-08-24 11:52
PlantUML files with `.puml` should work now : https://github.com/kernoeb/docker-docsify-pdf/issues/2

**Comment by johnholliday** [comment] 2022-08-24 13:01
Voila!  Working now...almost.
The PlantUML files are not rendering correctly.
I'm looking into this...

**Comment by johnholliday** [comment] 2022-08-24 16:01
![PDF generator - PUML files](https://user-images.githubusercontent.com/5294044/186466676-0113c28b-f13c-457d-a79c-124c2afdcb82.jpg)

**Comment by kernoeb** [comment] 2022-08-24 16:15
Good

Did you pull the last version, and use the import like this ? 

https://raw.githubusercontent.com/kernoeb/docker-docsify-pdf/main/docs/tutorials/documentation/test.md

(Can we continue the conversation on #2 ?)

**Closed** 2022-08-25 11:14 UTC
